[flake8]
max-line-length = 88

[tool.ruff]
ignore = [
    # Ignore line length check and let Black handle it
    "E501",

    # Ignore SyntaxError due to ruff not supporting pattern matching
    # https://github.com/charliermarsh/ruff/issues/282
    "E999",
]

# Assume Python 3.10.
target-version = "py310"
