name: Lint

on:
  push:

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2 # Check out the repository first.
      - name: Run prettier (JavaScript & TypeScript)
        run: |
          pushd frontend
          npm install
          npm run lint

      - name: Run black (Python formatting)
        uses: lgeiger/black-action@v1.0.1
        with:
          args: "./backend --experimental-string-processing --config ./backend/pyproject.toml"

      - name: Run ruff (Python linting)
        uses: jpetrucciani/ruff-check@main
        with:
          path: "./backend"
